// js/language.js - Sistema multilingua (IT, EN, ES, FR, DE, VEC)

let currentLang = localStorage.getItem('language') || 'it';

// Traduzioni complete
const translations = {
  it: {
    // Header
    app_title: 'Segnala Cestini Venezia',
    app_subtitle: 'Segnala un cestino pieno nel territorio comunale',
    // Footer nav
    nav_report: 'Segnala',
    nav_map: 'Mappa',
    nav_stats: 'Statistiche',
    nav_profile: 'Profilo',
    nav_info: 'Info',
    // Form
    photo_label: 'Foto del problema',
    add_photo: 'Aggiungi foto',
    photo_note: 'JPG · PNG · HEIC · max 1280 px',
    camera: 'Fotocamera',
    gallery: 'Galleria',
    photo_required: '⚠️ Almeno una foto è obbligatoria.',
    dest_title: 'A chi segnali?',
    dest_hint: 'Seleziona il destinatario principale.',
    dest_error: '⚠️ Seleziona un destinatario.',
    urgency: 'Urgenza',
    high: 'Alta — pericolo immediato',
    normal: 'Normale',
    low: 'Bassa — segnalazione informativa',
    description: 'Descrizione *',
    description_placeholder: 'Descrivi il problema...',
    name: 'Nome o Nickname *',
    email: 'Email *',
    email_note: '(ricevi la conferma di invio)',
    share_title: 'Condividi la segnalazione',
    your_data: 'I tuoi dati',
    share_hint: 'Diffondi il problema sui social',
    privacy: 'Ho letto e accetto l\'informativa privacy',
    send: 'Invia Segnalazione',
    sending: 'Invio in corso...',
    // Errori
    name_error: 'Inserisci il tuo nome o nickname.',
    email_error: 'Inserisci un indirizzo email valido.',
    descr_error: 'Inserisci una breve descrizione.',
    // Successo
    success_title: 'Segnalazione inviata!',
    success_msg: 'Il tuo report è stato trasmesso.',
    token_hint: 'Conserva questo codice per la risoluzione.',
    new_report: 'Nuova segnalazione',
    close: 'Chiudi',
    // Mappa
    map_title: 'Mappa delle segnalazioni',
    open_reports: 'Aperte',
    resolved_reports: 'Risolte',
    search_address: 'Cerca indirizzo',
    search_placeholder: 'Via/Piazza, città...',
    no_reports: 'Nessuna segnalazione trovata',
    remove_filters: 'Rimuovi filtri',
    legend_title: 'Urgenza',
    // Statistiche
    stats_title: 'Statistiche segnalazioni',
    total: 'Totali',
    open: 'Aperte',
    high_urgency: 'Alta urgenza',
    resolved: 'Risolte',
    filter_category: 'Filtra per categoria',
    all: 'Tutte',
    reports_by_category: 'Segnalazioni per categoria',
    by_urgency: 'Per urgenza',
    by_status: 'Per stato',
    trend: 'Andamento nel tempo',
    // Profilo
    profile_title: 'Le mie segnalazioni',
    my_reports: 'Le mie segnalazioni',
    no_reports_profile: 'Nessuna segnalazione trovata',
    search_by_email: 'Cerca per email',
    email_placeholder: 'Inserisci la tua email',
    search: 'Cerca',
    clear_data: 'Cancella dati',
    // Info
    info_title: 'Informazioni',
    how_it_works: 'Come funziona',
    // Avviso legale
    legal_warning: 'Le foto false o inappropriate costituiscono un illecito.',
    // Info page - nuove chiavi
    what_is_title: "Cos'è SegnalaCestiniVenezia",
    what_is_text: "SegnalaCestiniVenezia è uno strumento per segnalare cestini pieni e rifiuti abbandonati nel territorio di Venezia. Le segnalazioni vengono inviate a Veritas e al Comune di Venezia per un tempestivo intervento.",
    architecture_text: "Un'architettura semplice e trasparente: il sito è ospitato su GitHub Pages, i dati sono gestiti tramite Google Sheets e pubblicati come Open Data in formato CSV.",
    how_it_works_title: "Come funziona",
    how_it_works_step1: "Scatta una foto del cestino pieno o del rifiuto abbandonato",
    how_it_works_step2: "Verifica la posizione sulla mappa (GPS automatico o manuale)",
    how_it_works_step3: "Scegli la categoria, descrivi il problema e inserisci i tuoi dati",
    how_it_works_step4: "Invia la segnalazione — riceverai una conferma via email con ID e token",
    how_it_works_text: "Tutte le segnalazioni sono visibili sulla mappa pubblica e consultabili come Open Data.",
    resolve_title: "Come segnalare una risoluzione",
    resolve_step1: "Vai in Le mie segnalazioni e trova la segnalazione da chiudere",
    resolve_step2: "Clicca Segna come risolta — se hai il token salvato, l'invio è immediato",
    resolve_step3: "Altrimenti incolla il token ricevuto via email e clicca Conferma",
    resolve_note: "Il token di risoluzione è incluso nell'email di conferma inviata al momento della segnalazione.",
    profile_step1: "Accedi a Le mie segnalazioni per vedere tutte le segnalazioni inviate da questo dispositivo",
    profile_step2: "Lo stato si aggiorna automaticamente",
    profile_step3: "Puoi anche cercare le tue segnalazioni per email",
    navigate_title: "Naviga",
    my_profile: "Il mio profilo",
    opendata_title: "Open Data & Download",
    opendata_text: "Tutte le segnalazioni sono pubbliche e scaricabili liberamente in formato CSV, aggiornate automaticamente.",
    opendata_archives: "I dati sono suddivisi in due archivi:",
    open_reports_desc: "— in attesa di risoluzione",
    resolved_reports_desc: "— già chiuse",
    view_stats: "Vedi statistiche e dati",
    tech_title: "Tecnologie utilizzate",
    license_title: "Licenza e crediti",
    license_text: "Questo progetto è una versione modificata di SegnalaOra, realizzato da:",
    adaptation_text: "Adattamento per Venezia, sviluppo e personalizzazioni a cura di Francesco Bragadin.",
    license_cc_text: "Il progetto è distribuito con licenza Creative Commons Attribuzione 4.0 Internazionale (CC BY 4.0).",
    privacy_title: "Privacy & Cookie",
    privacy_text: "I dati personali (nome, email, posizione, foto) sono utilizzati esclusivamente per la gestione delle segnalazioni civiche, nel rispetto del GDPR 2016/679.",
    privacy_policy: "Privacy Policy",
    cookie_text: "Utilizziamo cookie analitici per migliorare il sito. Leggi la",
    accept: "Accetta",
    refuse: "Rifiuta",
    mark_resolved: "Segna come risolta",
  // Categorie problemi (aggiungi questo blocco)
   category_full_bins: 'Cestini pieni',
   category_abandoned_waste: 'Rifiuti abbandonati',
   category_road_surface: 'Manto stradale',
   category_street_lighting: 'Illuminazione pubblica',
   category_green_areas: 'Verde pubblico',
   category_mobility: 'Mobilità',
    category_full_bins_desc: 'Cestino pubblico da svuotare',
    category_abandoned_waste_desc: 'Rifiuti lasciati sul suolo pubblico',
    category_road_surface_desc: 'Buca o dissesto del manto stradale',
    category_street_lighting_desc: 'Lampione guasto o spento',
    category_green_areas_desc: 'Aiuola o area verde da manutenere',
    category_mobility_desc: 'Problema relativo a mobilità e trasporti',
    urgency_notes: 'Urgenza e note',
  },
  en: {
    app_title: 'Report Full Bins Venice',
    app_subtitle: 'Report a full bin in the municipal territory',
    nav_report: 'Report',
    nav_map: 'Map',
    nav_stats: 'Statistics',
    nav_profile: 'Profile',
    nav_info: 'Info',
    photo_label: 'Problem Photo',
    add_photo: 'Add photo',
    photo_note: 'JPG · PNG · HEIC · max 1280 px',
    camera: 'Camera',
    gallery: 'Gallery',
    photo_required: '⚠️ At least one photo is required.',
    dest_title: 'Who do you report to?',
    dest_hint: 'Select the main recipient.',
    dest_error: '⚠️ Select a recipient.',
    urgency: 'Urgency',
    high: 'High — immediate danger',
    normal: 'Normal',
    low: 'Low — informational report',
    description: 'Description *',
    description_placeholder: 'Describe the problem...',
    name: 'Name or Nickname *',
    email: 'Email *',
    email_note: '(you will receive confirmation)',
    share_title: 'Share the report',
    your_data: 'Your data',
    share_hint: 'Share on social media',
    privacy: 'I have read and accept the privacy policy',
    send: 'Send Report',
    sending: 'Sending...',
    name_error: 'Enter your name or nickname.',
    email_error: 'Enter a valid email address.',
    descr_error: 'Enter a brief description.',
    success_title: 'Report Sent!',
    success_msg: 'Your report has been submitted.',
    token_hint: 'Keep this code for resolution.',
    new_report: 'New report',
    close: 'Close',
    map_title: 'Reports Map',
    open_reports: 'Open',
    resolved_reports: 'Resolved',
    search_address: 'Search address',
    search_placeholder: 'Street/Square, city...',
    no_reports: 'No reports found',
    remove_filters: 'Remove filters',
    legend_title: 'Urgency',
    stats_title: 'Reports Statistics',
    total: 'Total',
    open: 'Open',
    high_urgency: 'High urgency',
    resolved: 'Resolved',
    filter_category: 'Filter by category',
    all: 'All',
    reports_by_category: 'Reports by category',
    by_urgency: 'By urgency',
    by_status: 'By status',
    trend: 'Trend over time',
    profile_title: 'My Reports',
    my_reports: 'My reports',
    no_reports_profile: 'No reports found',
    search_by_email: 'Search by email',
    email_placeholder: 'Enter your email',
    search: 'Search',
    clear_data: 'Clear data',
    info_title: 'Information',
    how_it_works: 'How it works',
    legal_warning: 'False or inappropriate photos constitute an offense.',
    what_is_title: "What is SegnalaCestiniVenezia",
    what_is_text: "SegnalaCestiniVenezia is a tool to report full bins and abandoned waste in the Venice area. Reports are sent to Veritas and the Municipality of Venice for timely intervention.",
    architecture_text: "A simple and transparent architecture: the site is hosted on GitHub Pages, data is managed via Google Sheets and published as Open Data in CSV format.",
    how_it_works_title: "How it works",
    how_it_works_step1: "Take a photo of the full bin or abandoned waste",
    how_it_works_step2: "Check the position on the map (automatic GPS or manual)",
    how_it_works_step3: "Choose the category, describe the problem and enter your data",
    how_it_works_step4: "Send the report — you will receive a confirmation email with ID and token",
    how_it_works_text: "All reports are visible on the public map and can be consulted as Open Data.",
    resolve_title: "How to report a resolution",
    resolve_step1: "Go to My reports and find the report to close",
    resolve_step2: "Click Mark as resolved — if you have the saved token, sending is immediate",
    resolve_step3: "Otherwise paste the token received by email and click Confirm",
    resolve_note: "The resolution token is included in the confirmation email sent at the time of the report.",
    profile_step1: "Access My reports to see all reports sent from this device",
    profile_step2: "The status updates automatically",
    profile_step3: "You can also search for your reports by email",
    navigate_title: "Navigate",
    my_profile: "My profile",
    opendata_title: "Open Data & Download",
    opendata_text: "All reports are public and freely downloadable in CSV format, automatically updated.",
    opendata_archives: "The data is divided into two archives:",
    open_reports_desc: "— awaiting resolution",
    resolved_reports_desc: "— already closed",
    view_stats: "View statistics and data",
    tech_title: "Technologies used",
    license_title: "License and credits",
    license_text: "This project is a modified version of SegnalaOra, created by:",
    adaptation_text: "Adaptation for Venice, development and customizations by Francesco Bragadin.",
    license_cc_text: "The project is distributed under the Creative Commons Attribution 4.0 International (CC BY 4.0) license.",
    privacy_title: "Privacy & Cookie",
    privacy_text: "Personal data (name, email, location, photos) are used exclusively for managing civic reports, in compliance with GDPR 2016/679.",
    privacy_policy: "Privacy Policy",
    cookie_text: "We use analytical cookies to improve the site. Read the",
    accept: "Accept",
    refuse: "Refuse",
    mark_resolved: "Mark as resolved",
    category_full_bins: 'Full bins',
  category_abandoned_waste: 'Abandoned waste',
  category_road_surface: 'Road surface',
  category_street_lighting: 'Street lighting',
  category_green_areas: 'Public green areas',
  category_mobility: 'Mobility',
    category_full_bins_desc: 'Public bin to empty',
category_abandoned_waste_desc: 'Waste left on public ground',
category_road_surface_desc: 'Pothole or road surface damage',
category_street_lighting_desc: 'Broken or off streetlight',
category_green_areas_desc: 'Flowerbed or green area to maintain',
category_mobility_desc: 'Mobility and transport issue',
    urgency_notes: 'Urgency and notes',
  },
  es: {
    app_title: 'Reportar Contenedores Llenos Venecia',
    app_subtitle: 'Reportar un contenedor lleno en el territorio municipal',
    nav_report: 'Reportar',
    nav_map: 'Mapa',
    nav_stats: 'Estadísticas',
    nav_profile: 'Perfil',
    nav_info: 'Info',
    photo_label: 'Foto del problema',
    add_photo: 'Añadir foto',
    photo_note: 'JPG · PNG · HEIC · máx 1280 px',
    camera: 'Cámara',
    gallery: 'Galería',
    photo_required: '⚠️ Se requiere al menos una foto.',
    dest_title: '¿A quién reportas?',
    dest_hint: 'Selecciona el destinatario principal.',
    dest_error: '⚠️ Selecciona un destinatario.',
    urgency: 'Urgencia',
    high: 'Alta — peligro inmediato',
    normal: 'Normal',
    low: 'Baja — reporte informativo',
    description: 'Descripción *',
    description_placeholder: 'Describe el problema...',
    name: 'Nombre o Apodo *',
    email: 'Correo electrónico *',
    email_note: '(recibirás confirmación)',
    share_title: 'Compartir el reporte',
    your_data: 'Tus datos',
    share_hint: 'Comparte en redes sociales',
    privacy: 'He leído y acepto la política de privacidad',
    send: 'Enviar Reporte',
    sending: 'Enviando...',
    name_error: 'Ingresa tu nombre o apodo.',
    email_error: 'Ingresa un correo electrónico válido.',
    descr_error: 'Ingresa una breve descripción.',
    success_title: '¡Reporte Enviado!',
    success_msg: 'Tu reporte ha sido transmitido.',
    token_hint: 'Guarda este código para la resolución.',
    new_report: 'Nuevo reporte',
    close: 'Cerrar',
    map_title: 'Mapa de Reportes',
    open_reports: 'Abiertas',
    resolved_reports: 'Resueltas',
    search_address: 'Buscar dirección',
    search_placeholder: 'Calle/Plaza, ciudad...',
    no_reports: 'No se encontraron reportes',
    remove_filters: 'Quitar filtros',
    legend_title: 'Urgencia',
    stats_title: 'Estadísticas de Reportes',
    total: 'Totales',
    open: 'Abiertas',
    high_urgency: 'Alta urgencia',
    resolved: 'Resueltas',
    filter_category: 'Filtrar por categoría',
    all: 'Todas',
    reports_by_category: 'Reportes por categoría',
    by_urgency: 'Por urgencia',
    by_status: 'Por estado',
    trend: 'Tendencia en el tiempo',
    profile_title: 'Mis Reportes',
    my_reports: 'Mis reportes',
    no_reports_profile: 'No se encontraron reportes',
    search_by_email: 'Buscar por correo',
    email_placeholder: 'Ingresa tu correo',
    search: 'Buscar',
    clear_data: 'Borrar datos',
    info_title: 'Información',
    how_it_works: 'Cómo funciona',
    legal_warning: 'Las fotos falsas o inapropiadas constituyen un delito.',
    what_is_title: "Qué es SegnalaCestiniVenezia",
    what_is_text: "SegnalaCestiniVenezia es una herramienta para reportar contenedores llenos y residuos abandonados en el territorio de Venecia. Los reportes se envían a Veritas y al Ayuntamiento de Venecia para una intervención oportuna.",
    architecture_text: "Una arquitectura simple y transparente: el sitio está alojado en GitHub Pages, los datos se gestionan a través de Google Sheets y se publican como Open Data en formato CSV.",
    how_it_works_title: "Cómo funciona",
    how_it_works_step1: "Toma una foto del contenedor lleno o residuo abandonado",
    how_it_works_step2: "Verifica la posición en el mapa (GPS automático o manual)",
    how_it_works_step3: "Elige la categoría, describe el problema e ingresa tus datos",
    how_it_works_step4: "Envía el reporte — recibirás un correo de confirmación con ID y token",
    how_it_works_text: "Todos los reportes son visibles en el mapa público y se pueden consultar como Open Data.",
    resolve_title: "Cómo reportar una resolución",
    resolve_step1: "Ve a Mis reportes y encuentra el reporte para cerrar",
    resolve_step2: "Haz clic en Marcar como resuelta — si tienes el token guardado, el envío es inmediato",
    resolve_step3: "De lo contrario, pega el token recibido por correo y haz clic en Confirmar",
    resolve_note: "El token de resolución está incluido en el correo de confirmación enviado al momento del reporte.",
    profile_step1: "Accede a Mis reportes para ver todos los reportes enviados desde este dispositivo",
    profile_step2: "El estado se actualiza automáticamente",
    profile_step3: "También puedes buscar tus reportes por correo electrónico",
    navigate_title: "Navegar",
    my_profile: "Mi perfil",
    opendata_title: "Open Data y Descarga",
    opendata_text: "Todos los reportes son públicos y descargables libremente en formato CSV, actualizados automáticamente.",
    opendata_archives: "Los datos se dividen en dos archivos:",
    open_reports_desc: "— en espera de resolución",
    resolved_reports_desc: "— ya cerradas",
    view_stats: "Ver estadísticas y datos",
    tech_title: "Tecnologías utilizadas",
    license_title: "Licencia y créditos",
    license_text: "Este proyecto es una versión modificada de SegnalaOra, realizado por:",
    adaptation_text: "Adaptación para Venecia, desarrollo y personalizaciones por Francesco Bragadin.",
    license_cc_text: "El proyecto se distribuye bajo licencia Creative Commons Attribution 4.0 International (CC BY 4.0).",
    privacy_title: "Privacidad y Cookies",
    privacy_text: "Los datos personales (nombre, correo, ubicación, fotos) se utilizan exclusivamente para la gestión de reportes ciudadanos, en cumplimiento del GDPR 2016/679.",
    privacy_policy: "Política de Privacidad",
    cookie_text: "Utilizamos cookies analíticas para mejorar el sitio. Lee la",
    accept: "Aceptar",
    refuse: "Rechazar",
    mark_resolved: "Marcar como resuelta",
    category_full_bins: 'Contenedores llenos',
    category_abandoned_waste: 'Residuos abandonados',
    category_road_surface: 'Capa de rodadura',
    category_street_lighting: 'Alumbrado público',
    category_green_areas: 'Zonas verdes',
    category_mobility: 'Movilidad',
    category_full_bins_desc: 'Contenedor público para vaciar',
category_abandoned_waste_desc: 'Residuos abandonados en el suelo',
category_road_surface_desc: 'Bacheca o daño en el pavimento',
category_street_lighting_desc: 'Farola rota o apagada',
category_green_areas_desc: 'Jardín o zona verde a mantener',
category_mobility_desc: 'Problema de movilidad y transporte',
     urgency_notes: 'Urgencia y notas',
  },
  fr: {
    app_title: 'Signaler Poubelles Pleines Venise',
    app_subtitle: 'Signaler une poubelle pleine sur le territoire municipal',
    nav_report: 'Signaler',
    nav_map: 'Carte',
    nav_stats: 'Statistiques',
    nav_profile: 'Profil',
    nav_info: 'Infos',
    photo_label: 'Photo du problème',
    add_photo: 'Ajouter une photo',
    photo_note: 'JPG · PNG · HEIC · max 1280 px',
    camera: 'Appareil photo',
    gallery: 'Galerie',
    photo_required: '⚠️ Au moins une photo est requise.',
    dest_title: 'À qui signalez-vous?',
    dest_hint: 'Sélectionnez le destinataire principal.',
    dest_error: '⚠️ Sélectionnez un destinataire.',
    urgency: 'Urgence',
    high: 'Élevée — danger immédiat',
    normal: 'Normale',
    low: 'Basse — signalement informatif',
    description: 'Description *',
    description_placeholder: 'Décrivez le problème...',
    name: 'Nom ou Surnom *',
    email: 'Email *',
    email_note: '(vous recevrez une confirmation)',
    share_title: 'Partager le signalement',
    your_data: 'Vos données',
    share_hint: 'Partagez sur les réseaux sociaux',
    privacy: 'J\'ai lu et j\'accepte la politique de confidentialité',
    send: 'Envoyer le signalement',
    sending: 'Envoi en cours...',
    name_error: 'Entrez votre nom ou surnom.',
    email_error: 'Entrez une adresse email valide.',
    descr_error: 'Entrez une brève description.',
    success_title: 'Signalement envoyé!',
    success_msg: 'Votre signalement a été transmis.',
    token_hint: 'Conservez ce code pour la résolution.',
    new_report: 'Nouveau signalement',
    close: 'Fermer',
    map_title: 'Carte des signalements',
    open_reports: 'Ouvertes',
    resolved_reports: 'Résolues',
    search_address: 'Chercher une adresse',
    search_placeholder: 'Rue/Place, ville...',
    no_reports: 'Aucun signalement trouvé',
    remove_filters: 'Supprimer les filtres',
    legend_title: 'Urgence',
    stats_title: 'Statistiques des signalements',
    total: 'Total',
    open: 'Ouvertes',
    high_urgency: 'Haute urgence',
    resolved: 'Résolues',
    filter_category: 'Filtrer par catégorie',
    all: 'Toutes',
    reports_by_category: 'Signalements par catégorie',
    by_urgency: 'Par urgence',
    by_status: 'Par statut',
    trend: 'Tendance dans le temps',
    profile_title: 'Mes signalements',
    my_reports: 'Mes signalements',
    no_reports_profile: 'Aucun signalement trouvé',
    search_by_email: 'Chercher par email',
    email_placeholder: 'Entrez votre email',
    search: 'Chercher',
    clear_data: 'Effacer les données',
    info_title: 'Informations',
    how_it_works: 'Comment ça fonctionne',
    legal_warning: 'Les fausses photos ou inappropriées constituent une infraction.',
    what_is_title: "Qu'est-ce que SegnalaCestiniVenezia",
    what_is_text: "SegnalaCestiniVenezia est un outil pour signaler les poubelles pleines et les déchets abandonnés sur le territoire de Venise. Les signalements sont envoyés à Veritas et à la Municipalité de Venise pour une intervention rapide.",
    architecture_text: "Une architecture simple et transparente : le site est hébergé sur GitHub Pages, les données sont gérées via Google Sheets et publiées en Open Data au format CSV.",
    how_it_works_title: "Comment ça fonctionne",
    how_it_works_step1: "Prenez une photo de la poubelle pleine ou des déchets abandonnés",
    how_it_works_step2: "Vérifiez la position sur la carte (GPS automatique ou manuel)",
    how_it_works_step3: "Choisissez la catégorie, décrivez le problème et entrez vos données",
    how_it_works_step4: "Envoyez le signalement — vous recevrez un email de confirmation avec ID et token",
    how_it_works_text: "Tous les signalements sont visibles sur la carte publique et consultables en Open Data.",
    resolve_title: "Comment signaler une résolution",
    resolve_step1: "Allez dans Mes signalements et trouvez le signalement à clôturer",
    resolve_step2: "Cliquez sur Marquer comme résolu — si vous avez le token sauvegardé, l'envoi est immédiat",
    resolve_step3: "Sinon, collez le token reçu par email et cliquez sur Confirmer",
    resolve_note: "Le token de résolution est inclus dans l'email de confirmation envoyé au moment du signalement.",
    profile_step1: "Accédez à Mes signalements pour voir tous les signalements envoyés depuis cet appareil",
    profile_step2: "Le statut se met à jour automatiquement",
    profile_step3: "Vous pouvez également rechercher vos signalements par email",
    navigate_title: "Naviguer",
    my_profile: "Mon profil",
    opendata_title: "Open Data & Téléchargement",
    opendata_text: "Tous les signalements sont publics et téléchargeables librement au format CSV, mis à jour automatiquement.",
    opendata_archives: "Les données sont divisées en deux archives :",
    open_reports_desc: "— en attente de résolution",
    resolved_reports_desc: "— déjà fermées",
    view_stats: "Voir les statistiques et données",
    tech_title: "Technologies utilisées",
    license_title: "Licence et crédits",
    license_text: "Ce projet est une version modifiée de SegnalaOra, réalisé par :",
    adaptation_text: "Adaptation pour Venise, développement et personnalisations par Francesco Bragadin.",
    license_cc_text: "Le projet est distribué sous licence Creative Commons Attribution 4.0 International (CC BY 4.0).",
    privacy_title: "Confidentialité et Cookies",
    privacy_text: "Les données personnelles (nom, email, position, photos) sont utilisées exclusivement pour la gestion des signalements citoyens, conformément au GDPR 2016/679.",
    privacy_policy: "Politique de confidentialité",
    cookie_text: "Nous utilisons des cookies analytiques pour améliorer le site. Lisez la",
    accept: "Accepter",
    refuse: "Refuser",
    mark_resolved: "Marquer comme résolu",
    category_full_bins: 'Poubelles pleines',
    category_abandoned_waste: 'Déchets abandonnés',
    category_road_surface: 'Chaussée',
    category_street_lighting: 'Éclairage public',
    category_green_areas: 'Espaces verts',
    category_mobility: 'Mobilité',
    category_full_bins_desc: 'Poubelle publique à vider',
category_abandoned_waste_desc: 'Déchets abandonnés sur la voie publique',
category_road_surface_desc: 'Nid-de-poule ou dégradation de la chaussée',
category_street_lighting_desc: 'Lampadaire cassé ou éteint',
category_green_areas_desc: 'Massif ou espace vert à entretenir',
category_mobility_desc: 'Problème de mobilité et de transport',
     urgency_notes: 'Urgence et notes',
  },
  de: {
    app_title: 'Volle Mülleimer Venedig melden',
    app_subtitle: 'Melden Sie einen vollen Mülleimer im Gemeindegebiet',
    nav_report: 'Melden',
    nav_map: 'Karte',
    nav_stats: 'Statistiken',
    nav_profile: 'Profil',
    nav_info: 'Info',
    photo_label: 'Foto des Problems',
    add_photo: 'Foto hinzufügen',
    photo_note: 'JPG · PNG · HEIC · max 1280 px',
    camera: 'Kamera',
    gallery: 'Galerie',
    photo_required: '⚠️ Mindestens ein Foto ist erforderlich.',
    dest_title: 'An wen melden Sie?',
    dest_hint: 'Wählen Sie den Hauptempfänger.',
    dest_error: '⚠️ Wählen Sie einen Empfänger.',
    urgency: 'Dringlichkeit',
    high: 'Hoch — unmittelbare Gefahr',
    normal: 'Normal',
    low: 'Niedrig — informativ',
    description: 'Beschreibung *',
    description_placeholder: 'Beschreiben Sie das Problem...',
    name: 'Name oder Spitzname *',
    email: 'E-Mail *',
    email_note: '(Sie erhalten eine Bestätigung)',
    share_title: 'Meldung teilen',
    your_data: 'Ihre Daten',
    share_hint: 'In sozialen Netzwerken teilen',
    privacy: 'Ich habe die Datenschutzerklärung gelesen und akzeptiere sie',
    send: 'Meldung senden',
    sending: 'Senden...',
    name_error: 'Geben Sie Ihren Namen oder Spitznamen ein.',
    email_error: 'Geben Sie eine gültige E-Mail-Adresse ein.',
    descr_error: 'Geben Sie eine kurze Beschreibung ein.',
    success_title: 'Meldung gesendet!',
    success_msg: 'Ihre Meldung wurde übermittelt.',
    token_hint: 'Bewahren Sie diesen Code für die Lösung auf.',
    new_report: 'Neue Meldung',
    close: 'Schließen',
    map_title: 'Karte der Meldungen',
    open_reports: 'Offen',
    resolved_reports: 'Erledigt',
    search_address: 'Adresse suchen',
    search_placeholder: 'Straße/Platz, Stadt...',
    no_reports: 'Keine Meldungen gefunden',
    remove_filters: 'Filter entfernen',
    legend_title: 'Dringlichkeit',
    stats_title: 'Meldungsstatistiken',
    total: 'Insgesamt',
    open: 'Offen',
    high_urgency: 'Hohe Dringlichkeit',
    resolved: 'Erledigt',
    filter_category: 'Nach Kategorie filtern',
    all: 'Alle',
    reports_by_category: 'Meldungen nach Kategorie',
    by_urgency: 'Nach Dringlichkeit',
    by_status: 'Nach Status',
    trend: 'Zeitlicher Verlauf',
    profile_title: 'Meine Meldungen',
    my_reports: 'Meine Meldungen',
    no_reports_profile: 'Keine Meldungen gefunden',
    search_by_email: 'Nach E-Mail suchen',
    email_placeholder: 'Geben Sie Ihre E-Mail ein',
    search: 'Suchen',
    clear_data: 'Daten löschen',
    info_title: 'Informationen',
    how_it_works: 'So funktioniert es',
    legal_warning: 'Falsche oder unangemessene Fotos sind eine Straftat.',
    what_is_title: "Was ist SegnalaCestiniVenezia",
    what_is_text: "SegnalaCestiniVenezia ist ein Werkzeug, um volle Mülleimer und zurückgelassene Abfälle im Gebiet von Venedig zu melden. Die Meldungen werden an Veritas und die Gemeinde Venedig gesendet, um schnell eingreifen zu können.",
    architecture_text: "Eine einfache und transparente Architektur: Die Website wird auf GitHub Pages gehostet, die Daten werden über Google Sheets verwaltet und als Open Data im CSV-Format veröffentlicht.",
    how_it_works_title: "So funktioniert es",
    how_it_works_step1: "Machen Sie ein Foto vom vollen Mülleimer oder zurückgelassenen Abfall",
    how_it_works_step2: "Überprüfen Sie die Position auf der Karte (automatisches GPS oder manuell)",
    how_it_works_step3: "Wählen Sie die Kategorie, beschreiben Sie das Problem und geben Sie Ihre Daten ein",
    how_it_works_step4: "Senden Sie die Meldung — Sie erhalten eine Bestätigungs-E-Mail mit ID und Token",
    how_it_works_text: "Alle Meldungen sind auf der öffentlichen Karte sichtbar und als Open Data einsehbar.",
    resolve_title: "Wie man eine Lösung meldet",
    resolve_step1: "Gehen Sie zu Meine Meldungen und finden Sie die zu schließende Meldung",
    resolve_step2: "Klicken Sie auf Als erledigt markieren — wenn Sie das gespeicherte Token haben, ist das Senden sofort",
    resolve_step3: "Fügen Sie andernfalls das per E-Mail erhaltene Token ein und klicken Sie auf Bestätigen",
    resolve_note: "Das Lösungstoken ist in der Bestätigungs-E-Mail enthalten, die zum Zeitpunkt der Meldung gesendet wurde.",
    profile_step1: "Rufen Sie Meine Meldungen auf, um alle von diesem Gerät gesendeten Meldungen zu sehen",
    profile_step2: "Der Status wird automatisch aktualisiert",
    profile_step3: "Sie können auch nach Ihren Meldungen per E-Mail suchen",
    navigate_title: "Navigieren",
    my_profile: "Mein Profil",
    opendata_title: "Open Data & Download",
    opendata_text: "Alle Meldungen sind öffentlich und können frei als CSV heruntergeladen werden, automatisch aktualisiert.",
    opendata_archives: "Die Daten sind in zwei Archive unterteilt:",
    open_reports_desc: "— in Erwartung der Lösung",
    resolved_reports_desc: "— bereits geschlossen",
    view_stats: "Statistiken und Daten anzeigen",
    tech_title: "Verwendete Technologien",
    license_title: "Lizenz und Credits",
    license_text: "Dieses Projekt ist eine modifizierte Version von SegnalaOra, erstellt von:",
    adaptation_text: "Anpassung für Venedig, Entwicklung und Anpassungen von Francesco Bragadin.",
    license_cc_text: "Das Projekt wird unter der Creative Commons Attribution 4.0 International (CC BY 4.0) Lizenz vertrieben.",
    privacy_title: "Datenschutz & Cookie",
    privacy_text: "Personenbezogene Daten (Name, E-Mail, Standort, Fotos) werden ausschließlich für die Verwaltung von Bürgermeldungen verwendet, in Übereinstimmung mit der DSGVO 2016/679.",
    privacy_policy: "Datenschutzerklärung",
    cookie_text: "Wir verwenden analytische Cookies, um die Website zu verbessern. Lesen Sie die",
    accept: "Akzeptieren",
    refuse: "Ablehnen",
    mark_resolved: "Als erledigt markieren",
    category_full_bins: 'Volle Mülleimer',
    category_abandoned_waste: 'Zurückgelassener Abfall',
    category_road_surface: 'Straßenbelag',
    category_street_lighting: 'Straßenbeleuchtung',
    category_green_areas: 'Grünflächen',
    category_mobility: 'Mobilität',
    category_full_bins_desc: 'Öffentlicher Mülleimer zu leeren',
category_abandoned_waste_desc: 'Abfall auf öffentlichem Grund',
category_road_surface_desc: 'Schlagloch oder Straßenschaden',
category_street_lighting_desc: 'Defekte oder ausgeschaltete Straßenlaterne',
category_green_areas_desc: 'Blumenbeet oder Grünfläche zu pflegen',
category_mobility_desc: 'Mobilitäts- und Verkehrsproblem',
    urgency_notes: 'Dringlichkeit und Notizen',
  },
  vec: {
    app_title: 'Segnala Cestini Venesia',
    app_subtitle: 'Segnala un cestin pien nel teritorio comunal',
    nav_report: 'Segnala',
    nav_map: 'Mapa',
    nav_stats: 'Statìsteghe',
    nav_profile: 'Profilo',
    nav_info: 'Info',
    photo_label: 'Foto del problema',
    add_photo: 'Zonta foto',
    photo_note: 'JPG · PNG · HEIC · max 1280 px',
    camera: 'Fotocàmara',
    gallery: 'Galeria',
    photo_required: '⚠️ Almanco na foto la xe obligatoria.',
    dest_title: 'A chi te segnali?',
    dest_hint: 'Siegli el destinatario prinsipal.',
    dest_error: '⚠️ Siegli un destinatario.',
    urgency: 'Urgensa',
    high: 'Alta — pericolo imediato',
    normal: 'Normale',
    low: 'Basa — segnalassion informativa',
    description: 'Descression *',
    description_placeholder: 'Descrivi el problema...',
    name: 'Nome o Siornome *',
    email: 'Email *',
    email_note: '(te rivarà conferma)',
    share_title: 'Condividi la segnalassion',
    your_data: 'I to dati',
    share_hint: 'Spara sui social',
    privacy: 'Go leto e acetà la privacy',
    send: 'Manda Segnalassion',
    sending: 'Mando in corso...',
    name_error: 'Meti el to nome o siornome.',
    email_error: 'Meti na email valida.',
    descr_error: 'Meti na breve descression.',
    success_title: 'Segnalassion mandà!',
    success_msg: 'El to report el xe sta trasmesso.',
    token_hint: 'Tegnito sto codice par la risolussion.',
    new_report: 'Nova segnalassion',
    close: 'Sara',
    map_title: 'Mapa de le segnalassion',
    open_reports: 'Averte',
    resolved_reports: 'Risolte',
    search_address: 'Serca indiriso',
    search_placeholder: 'Via/Piasa, sità...',
    no_reports: 'Nisuna segnalassion trovà',
    remove_filters: 'Leva i filtri',
    legend_title: 'Urgensa',
    stats_title: 'Statìsteghe segnalassion',
    total: 'Totale',
    open: 'Averte',
    high_urgency: 'Alta urgensa',
    resolved: 'Risolte',
    filter_category: 'Filtra par categoria',
    all: 'Tute',
    reports_by_category: 'Segnalassion par categoria',
    by_urgency: 'Par urgensa',
    by_status: 'Par stato',
    trend: 'Andamento nel tenpo',
    profile_title: 'Le mie segnalassion',
    my_reports: 'Le mie segnalassion',
    no_reports_profile: 'Nisuna segnalassion trovà',
    search_by_email: 'Serca par email',
    email_placeholder: 'Meti la to email',
    search: 'Serca',
    clear_data: 'Cancela dati',
    info_title: 'Informassion',
    how_it_works: 'Come che funsiona',
    legal_warning: 'Le foto false o inaproprie le xe un ilesito.',
    what_is_title: "Cossa che xe SegnalaCestiniVenesia",
    what_is_text: "SegnalaCestiniVenesia el xe un strumento par segnalar cestini pieni e rifiuti abandonà nel teritorio de Venesia. Le segnalazion le vien invià a Veritas e al Comun de Venesia par un intervento tempestivo.",
    architecture_text: "Na architetura senplice e trasparente: el sito el xe ospità su GitHub Pages, i dati i xe gestii tramite Google Sheets e publicà come Open Data in formato CSV.",
    how_it_works_title: "Come che funsiona",
    how_it_works_step1: "Scatta na foto del cestino pieno o del rifiuto abandonà",
    how_it_works_step2: "Verifica la posizion sulla mapa (GPS automatico o manuale)",
    how_it_works_step3: "Siegli la categoria, descrivi el problema e inserissi i to dati",
    how_it_works_step4: "Invia la segnalassion — te rivarà na conferma via email con ID e token",
    how_it_works_text: "Tute le segnalazion le xe visibili sulla mapa publica e consultabili come Open Data.",
    resolve_title: "Come segnalar na risolussion",
    resolve_step1: "Và in Le mie segnalazion e cata la segnalassion da sara",
    resolve_step2: "Clicca Segna come risolta — se te ghè el token salvà, l'invio el xe imediato",
    resolve_step3: "Se no incolla el token ricevù via email e clicca Conferma",
    resolve_note: "El token de risolussion el xe incluso nell'email de conferma invià al momento de la segnalassion.",
    profile_step1: "Và in Le mie segnalazion par veder tute le segnalazion invià da sto dispositivo",
    profile_step2: "Lo stato el se aggiorna automaticamente",
    profile_step3: "Te pol anche cercar le to segnalazion par email",
    navigate_title: "Naviga",
    my_profile: "El mio profilo",
    opendata_title: "Open Data & Download",
    opendata_text: "Tute le segnalazion le xe pubbliche e scaricabili liberamente in formato CSV, aggiornà automaticamente.",
    opendata_archives: "I dati i xe suddivisi in do archivi:",
    open_reports_desc: "— in atesa de risolussion",
    resolved_reports_desc: "— za sarà",
    view_stats: "Varda statìsteghe e dati",
    tech_title: "Tecnologie doperà",
    license_title: "Licensa e crediti",
    license_text: "Sto progetto el xe na version modificà de SegnalaOra, realizzà da:",
    adaptation_text: "Adatamento par Venesia, sviluppo e personalizzazion a cura de Francesco Bragadin.",
    license_cc_text: "El progetto el xe distribuìo co licensa Creative Commons Attribuzione 4.0 Internazionale (CC BY 4.0).",
    privacy_title: "Privacy & Cookie",
    privacy_text: "I dati personali (nome, email, posizion, foto) i xe doperà esclusivamente par la gestion de le segnalazion civiche, rispetando el GDPR 2016/679.",
    privacy_policy: "Politega de Privacy",
    cookie_text: "Doparimo cookie analitici par mejorar el sito. Lesi la",
    accept: "Aceta",
    refuse: "Rifiuta",
    mark_resolved: "Segna come risolta",
    category_full_bins: 'Cestini pieni',
    category_abandoned_waste: 'Rifiuti abandonà',
    category_road_surface: 'Manto stradałe',
    category_street_lighting: 'Inluminassion publica',
    category_green_areas: 'Verde publico',
    category_mobility: 'Mobilità',
    category_full_bins_desc: 'Cestin publico da svodar',
category_abandoned_waste_desc: 'Rifiuti abandonà sul teren publico',
category_road_surface_desc: 'Buca o rovinadura del manto stradałe',
category_street_lighting_desc: 'Lampion roto o spento',
category_green_areas_desc: 'Aiuola o area verde da mantegnar',
category_mobility_desc: 'Problema de mobilità e trasporti',
     urgency_notes: 'Urgensa e note',
  }
};

// Funzioni principali
function toggleLangMenu() {
  const menu = document.getElementById('langMenu');
    if (menu) {
    menu.classList.toggle('open');
}
}

function setLanguage(lang) {
  currentLang = lang;
  localStorage.setItem('language', currentLang);
  updateUILanguage();
  updateButtonText();
  
  // RIGENERA LE CATEGORIE (se la funzione esiste)
  if (typeof loadDestinatari === 'function') {
    loadDestinatari();
  }
  
  // Chiudi il menu
  const menu = document.getElementById('langMenu');
  if (menu) menu.classList.remove('open');
}

function updateUILanguage() {
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (translations[currentLang] && translations[currentLang][key]) {
      if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
        if (el.placeholder !== undefined) {
          el.placeholder = translations[currentLang][key];
        } else {
          el.value = translations[currentLang][key];
        }
      } else {
        el.textContent = translations[currentLang][key];
      }
    }
  });
}

function updateButtonText() {
  const langText = document.getElementById('langText');
  if (langText) {
    const codes = { it: 'IT', en: 'EN', es: 'ES', fr: 'FR', de: 'DE', vec: 'VEC' };
    langText.textContent = codes[currentLang] || 'IT';
  }
}

function initLanguage() {
  updateUILanguage();
  updateButtonText();
  // Chiudi menu se si clicca fuori
  document.addEventListener('click', function(e) {
    const dropdown = document.querySelector('.lang-dropdown');
    const menu = document.getElementById('langMenu');
    if (dropdown && menu && !dropdown.contains(e.target)) {
      menu.classList.remove('open');
    }
  });
}

document.addEventListener('DOMContentLoaded', initLanguage);
