// js/language.js - Sistema multilingua (IT, EN, ES, FR, DE, VEC)

let currentLang = localStorage.getItem('language') || 'it';

// Traduzioni complete
const translations = {
  it: {
    // Header
    app_title: 'Segnala Cestini Venezia',
    app_subtitle: 'Segnala un cestino pieno nel territorio comunale',
    // Footer nav
    nav_report: 'Segnala',
    nav_map: 'Mappa',
    nav_stats: 'Statistiche',
    nav_profile: 'Profilo',
    nav_info: 'Info',
    // Form
    photo_label: 'Foto del problema',
    add_photo: 'Aggiungi foto',
    photo_note: 'JPG · PNG · HEIC · max 1280 px',
    camera: 'Fotocamera',
    gallery: 'Galleria',
    photo_required: '⚠️ Almeno una foto è obbligatoria.',
    dest_title: 'A chi segnali?',
    dest_hint: 'Seleziona il destinatario principale.',
    dest_error: '⚠️ Seleziona un destinatario.',
    urgency: 'Urgenza',
    high: 'Alta — pericolo immediato',
    normal: 'Normale',
    low: 'Bassa — segnalazione informativa',
    description: 'Descrizione *',
    description_placeholder: 'Descrivi il problema...',
    name: 'Nome o Nickname *',
    email: 'Email *',
    email_note: '(ricevi la conferma di invio)',
    share_title: 'Condividi la segnalazione',
    share_hint: 'Diffondi il problema sui social',
    privacy: 'Ho letto e accetto l\'informativa privacy',
    send: 'Invia Segnalazione',
    sending: 'Invio in corso...',
    // Errori
    name_error: 'Inserisci il tuo nome o nickname.',
    email_error: 'Inserisci un indirizzo email valido.',
    descr_error: 'Inserisci una breve descrizione.',
    // Successo
    success_title: 'Segnalazione inviata!',
    success_msg: 'Il tuo report è stato trasmesso.',
    token_hint: 'Conserva questo codice per la risoluzione.',
    new_report: 'Nuova segnalazione',
    close: 'Chiudi',
    // Mappa
    map_title: 'Mappa delle segnalazioni',
    open_reports: 'Aperte',
    resolved_reports: 'Risolte',
    search_address: 'Cerca indirizzo',
    search_placeholder: 'Via/Piazza, città...',
    no_reports: 'Nessuna segnalazione trovata',
    remove_filters: 'Rimuovi filtri',
    legend_title: 'Urgenza',
    // Statistiche
    stats_title: 'Statistiche segnalazioni',
    total: 'Totali',
    open: 'Aperte',
    high_urgency: 'Alta urgenza',
    resolved: 'Risolte',
    filter_category: 'Filtra per categoria',
    all: 'Tutte',
    reports_by_category: 'Segnalazioni per categoria',
    by_urgency: 'Per urgenza',
    by_status: 'Per stato',
    trend: 'Andamento nel tempo',
    // Profilo
    profile_title: 'Le mie segnalazioni',
    my_reports: 'Le mie segnalazioni',
    no_reports_profile: 'Nessuna segnalazione trovata',
    search_by_email: 'Cerca per email',
    email_placeholder: 'Inserisci la tua email',
    search: 'Cerca',
    clear_data: 'Cancella dati',
    // Info
    info_title: 'Informazioni',
    how_it_works: 'Come funziona',
    // Avviso legale
    legal_warning: 'Le foto false o inappropriate costituiscono un illecito.'
  },
  en: {
    app_title: 'Report Full Bins Venice',
    app_subtitle: 'Report a full bin in the municipal territory',
    nav_report: 'Report',
    nav_map: 'Map',
    nav_stats: 'Statistics',
    nav_profile: 'Profile',
    nav_info: 'Info',
    photo_label: 'Problem Photo',
    add_photo: 'Add photo',
    photo_note: 'JPG · PNG · HEIC · max 1280 px',
    camera: 'Camera',
    gallery: 'Gallery',
    photo_required: '⚠️ At least one photo is required.',
    dest_title: 'Who do you report to?',
    dest_hint: 'Select the main recipient.',
    dest_error: '⚠️ Select a recipient.',
    urgency: 'Urgency',
    high: 'High — immediate danger',
    normal: 'Normal',
    low: 'Low — informational report',
    description: 'Description *',
    description_placeholder: 'Describe the problem...',
    name: 'Name or Nickname *',
    email: 'Email *',
    email_note: '(you will receive confirmation)',
    share_title: 'Share the report',
    share_hint: 'Share on social media',
    privacy: 'I have read and accept the privacy policy',
    send: 'Send Report',
    sending: 'Sending...',
    name_error: 'Enter your name or nickname.',
    email_error: 'Enter a valid email address.',
    descr_error: 'Enter a brief description.',
    success_title: 'Report Sent!',
    success_msg: 'Your report has been submitted.',
    token_hint: 'Keep this code for resolution.',
    new_report: 'New report',
    close: 'Close',
    map_title: 'Reports Map',
    open_reports: 'Open',
    resolved_reports: 'Resolved',
    search_address: 'Search address',
    search_placeholder: 'Street/Square, city...',
    no_reports: 'No reports found',
    remove_filters: 'Remove filters',
    legend_title: 'Urgency',
    stats_title: 'Reports Statistics',
    total: 'Total',
    open: 'Open',
    high_urgency: 'High urgency',
    resolved: 'Resolved',
    filter_category: 'Filter by category',
    all: 'All',
    reports_by_category: 'Reports by category',
    by_urgency: 'By urgency',
    by_status: 'By status',
    trend: 'Trend over time',
    profile_title: 'My Reports',
    my_reports: 'My reports',
    no_reports_profile: 'No reports found',
    search_by_email: 'Search by email',
    email_placeholder: 'Enter your email',
    search: 'Search',
    clear_data: 'Clear data',
    info_title: 'Information',
    how_it_works: 'How it works',
    legal_warning: 'False or inappropriate photos constitute an offense.'
  },
  es: {
    app_title: 'Reportar Contenedores Llenos Venecia',
    app_subtitle: 'Reportar un contenedor lleno en el territorio municipal',
    nav_report: 'Reportar',
    nav_map: 'Mapa',
    nav_stats: 'Estadísticas',
    nav_profile: 'Perfil',
    nav_info: 'Info',
    photo_label: 'Foto del problema',
    add_photo: 'Añadir foto',
    photo_note: 'JPG · PNG · HEIC · máx 1280 px',
    camera: 'Cámara',
    gallery: 'Galería',
    photo_required: '⚠️ Se requiere al menos una foto.',
    dest_title: '¿A quién reportas?',
    dest_hint: 'Selecciona el destinatario principal.',
    dest_error: '⚠️ Selecciona un destinatario.',
    urgency: 'Urgencia',
    high: 'Alta — peligro inmediato',
    normal: 'Normal',
    low: 'Baja — reporte informativo',
    description: 'Descripción *',
    description_placeholder: 'Describe el problema...',
    name: 'Nombre o Apodo *',
    email: 'Correo electrónico *',
    email_note: '(recibirás confirmación)',
    share_title: 'Compartir el reporte',
    share_hint: 'Comparte en redes sociales',
    privacy: 'He leído y acepto la política de privacidad',
    send: 'Enviar Reporte',
    sending: 'Enviando...',
    name_error: 'Ingresa tu nombre o apodo.',
    email_error: 'Ingresa un correo electrónico válido.',
    descr_error: 'Ingresa una breve descripción.',
    success_title: '¡Reporte Enviado!',
    success_msg: 'Tu reporte ha sido transmitido.',
    token_hint: 'Guarda este código para la resolución.',
    new_report: 'Nuevo reporte',
    close: 'Cerrar',
    map_title: 'Mapa de Reportes',
    open_reports: 'Abiertas',
    resolved_reports: 'Resueltas',
    search_address: 'Buscar dirección',
    search_placeholder: 'Calle/Plaza, ciudad...',
    no_reports: 'No se encontraron reportes',
    remove_filters: 'Quitar filtros',
    legend_title: 'Urgencia',
    stats_title: 'Estadísticas de Reportes',
    total: 'Totales',
    open: 'Abiertas',
    high_urgency: 'Alta urgencia',
    resolved: 'Resueltas',
    filter_category: 'Filtrar por categoría',
    all: 'Todas',
    reports_by_category: 'Reportes por categoría',
    by_urgency: 'Por urgencia',
    by_status: 'Por estado',
    trend: 'Tendencia en el tiempo',
    profile_title: 'Mis Reportes',
    my_reports: 'Mis reportes',
    no_reports_profile: 'No se encontraron reportes',
    search_by_email: 'Buscar por correo',
    email_placeholder: 'Ingresa tu correo',
    search: 'Buscar',
    clear_data: 'Borrar datos',
    info_title: 'Información',
    how_it_works: 'Cómo funciona',
    legal_warning: 'Las fotos falsas o inapropiadas constituyen un delito.'
  },
  fr: {
    app_title: 'Signaler Poubelles Pleines Venise',
    app_subtitle: 'Signaler une poubelle pleine sur le territoire municipal',
    nav_report: 'Signaler',
    nav_map: 'Carte',
    nav_stats: 'Statistiques',
    nav_profile: 'Profil',
    nav_info: 'Infos',
    photo_label: 'Photo du problème',
    add_photo: 'Ajouter une photo',
    photo_note: 'JPG · PNG · HEIC · max 1280 px',
    camera: 'Appareil photo',
    gallery: 'Galerie',
    photo_required: '⚠️ Au moins une photo est requise.',
    dest_title: 'À qui signalez-vous?',
    dest_hint: 'Sélectionnez le destinataire principal.',
    dest_error: '⚠️ Sélectionnez un destinataire.',
    urgency: 'Urgence',
    high: 'Élevée — danger immédiat',
    normal: 'Normale',
    low: 'Basse — signalement informatif',
    description: 'Description *',
    description_placeholder: 'Décrivez le problème...',
    name: 'Nom ou Surnom *',
    email: 'Email *',
    email_note: '(vous recevrez une confirmation)',
    share_title: 'Partager le signalement',
    share_hint: 'Partagez sur les réseaux sociaux',
    privacy: 'J\'ai lu et j\'accepte la politique de confidentialité',
    send: 'Envoyer le signalement',
    sending: 'Envoi en cours...',
    name_error: 'Entrez votre nom ou surnom.',
    email_error: 'Entrez une adresse email valide.',
    descr_error: 'Entrez une brève description.',
    success_title: 'Signalement envoyé!',
    success_msg: 'Votre signalement a été transmis.',
    token_hint: 'Conservez ce code pour la résolution.',
    new_report: 'Nouveau signalement',
    close: 'Fermer',
    map_title: 'Carte des signalements',
    open_reports: 'Ouvertes',
    resolved_reports: 'Résolues',
    search_address: 'Chercher une adresse',
    search_placeholder: 'Rue/Place, ville...',
    no_reports: 'Aucun signalement trouvé',
    remove_filters: 'Supprimer les filtres',
    legend_title: 'Urgence',
    stats_title: 'Statistiques des signalements',
    total: 'Total',
    open: 'Ouvertes',
    high_urgency: 'Haute urgence',
    resolved: 'Résolues',
    filter_category: 'Filtrer par catégorie',
    all: 'Toutes',
    reports_by_category: 'Signalements par catégorie',
    by_urgency: 'Par urgence',
    by_status: 'Par statut',
    trend: 'Tendance dans le temps',
    profile_title: 'Mes signalements',
    my_reports: 'Mes signalements',
    no_reports_profile: 'Aucun signalement trouvé',
    search_by_email: 'Chercher par email',
    email_placeholder: 'Entrez votre email',
    search: 'Chercher',
    clear_data: 'Effacer les données',
    info_title: 'Informations',
    how_it_works: 'Comment ça fonctionne',
    legal_warning: 'Les fausses photos ou inappropriées constituent une infraction.'
  },
  de: {
    app_title: 'Volle Mülleimer Venedig melden',
    app_subtitle: 'Melden Sie einen vollen Mülleimer im Gemeindegebiet',
    nav_report: 'Melden',
    nav_map: 'Karte',
    nav_stats: 'Statistiken',
    nav_profile: 'Profil',
    nav_info: 'Info',
    photo_label: 'Foto des Problems',
    add_photo: 'Foto hinzufügen',
    photo_note: 'JPG · PNG · HEIC · max 1280 px',
    camera: 'Kamera',
    gallery: 'Galerie',
    photo_required: '⚠️ Mindestens ein Foto ist erforderlich.',
    dest_title: 'An wen melden Sie?',
    dest_hint: 'Wählen Sie den Hauptempfänger.',
    dest_error: '⚠️ Wählen Sie einen Empfänger.',
    urgency: 'Dringlichkeit',
    high: 'Hoch — unmittelbare Gefahr',
    normal: 'Normal',
    low: 'Niedrig — informativ',
    description: 'Beschreibung *',
    description_placeholder: 'Beschreiben Sie das Problem...',
    name: 'Name oder Spitzname *',
    email: 'E-Mail *',
    email_note: '(Sie erhalten eine Bestätigung)',
    share_title: 'Meldung teilen',
    share_hint: 'In sozialen Netzwerken teilen',
    privacy: 'Ich habe die Datenschutzerklärung gelesen und akzeptiere sie',
    send: 'Meldung senden',
    sending: 'Senden...',
    name_error: 'Geben Sie Ihren Namen oder Spitznamen ein.',
    email_error: 'Geben Sie eine gültige E-Mail-Adresse ein.',
    descr_error: 'Geben Sie eine kurze Beschreibung ein.',
    success_title: 'Meldung gesendet!',
    success_msg: 'Ihre Meldung wurde übermittelt.',
    token_hint: 'Bewahren Sie diesen Code für die Lösung auf.',
    new_report: 'Neue Meldung',
    close: 'Schließen',
    map_title: 'Karte der Meldungen',
    open_reports: 'Offen',
    resolved_reports: 'Erledigt',
    search_address: 'Adresse suchen',
    search_placeholder: 'Straße/Platz, Stadt...',
    no_reports: 'Keine Meldungen gefunden',
    remove_filters: 'Filter entfernen',
    legend_title: 'Dringlichkeit',
    stats_title: 'Meldungsstatistiken',
    total: 'Insgesamt',
    open: 'Offen',
    high_urgency: 'Hohe Dringlichkeit',
    resolved: 'Erledigt',
    filter_category: 'Nach Kategorie filtern',
    all: 'Alle',
    reports_by_category: 'Meldungen nach Kategorie',
    by_urgency: 'Nach Dringlichkeit',
    by_status: 'Nach Status',
    trend: 'Zeitlicher Verlauf',
    profile_title: 'Meine Meldungen',
    my_reports: 'Meine Meldungen',
    no_reports_profile: 'Keine Meldungen gefunden',
    search_by_email: 'Nach E-Mail suchen',
    email_placeholder: 'Geben Sie Ihre E-Mail ein',
    search: 'Suchen',
    clear_data: 'Daten löschen',
    info_title: 'Informationen',
    how_it_works: 'So funktioniert es',
    legal_warning: 'Falsche oder unangemessene Fotos sind eine Straftat.'
  },
  vec: {
    app_title: 'Segnala Cestini Venesia',
    app_subtitle: 'Segnala un cestin pien nel teritorio comunal',
    nav_report: 'Segnala',
    nav_map: 'Mapa',
    nav_stats: 'Statìsteghe',
    nav_profile: 'Profilo',
    nav_info: 'Info',
    photo_label: 'Foto del problema',
    add_photo: 'Zonta foto',
    photo_note: 'JPG · PNG · HEIC · max 1280 px',
    camera: 'Fotocàmara',
    gallery: 'Galeria',
    photo_required: '⚠️ Almanco na foto la xe obligatoria.',
    dest_title: 'A chi te segnali?',
    dest_hint: 'Siegli el destinatario prinsipal.',
    dest_error: '⚠️ Siegli un destinatario.',
    urgency: 'Urgensa',
    high: 'Alta — pericolo imediato',
    normal: 'Normale',
    low: 'Basa — segnalassion informativa',
    description: 'Descression *',
    description_placeholder: 'Descrivi el problema...',
    name: 'Nome o Siornome *',
    email: 'Email *',
    email_note: '(te rivarà conferma)',
    share_title: 'Condividi la segnalassion',
    share_hint: 'Spara sui social',
    privacy: 'Go leto e acetà la privacy',
    send: 'Manda Segnalassion',
    sending: 'Mando in corso...',
    name_error: 'Meti el to nome o siornome.',
    email_error: 'Meti na email valida.',
    descr_error: 'Meti na breve descression.',
    success_title: 'Segnalassion mandà!',
    success_msg: 'El to report el xe sta trasmesso.',
    token_hint: 'Tegnito sto codice par la risolussion.',
    new_report: 'Nova segnalassion',
    close: 'Sara',
    map_title: 'Mapa de le segnalassion',
    open_reports: 'Averte',
    resolved_reports: 'Risolte',
    search_address: 'Serca indiriso',
    search_placeholder: 'Via/Piasa, sità...',
    no_reports: 'Nisuna segnalassion trovà',
    remove_filters: 'Leva i filtri',
    legend_title: 'Urgensa',
    stats_title: 'Statìsteghe segnalassion',
    total: 'Totale',
    open: 'Averte',
    high_urgency: 'Alta urgensa',
    resolved: 'Risolte',
    filter_category: 'Filtra par categoria',
    all: 'Tute',
    reports_by_category: 'Segnalassion par categoria',
    by_urgency: 'Par urgensa',
    by_status: 'Par stato',
    trend: 'Andamento nel tenpo',
    profile_title: 'Le mie segnalassion',
    my_reports: 'Le mie segnalassion',
    no_reports_profile: 'Nisuna segnalassion trovà',
    search_by_email: 'Serca par email',
    email_placeholder: 'Meti la to email',
    search: 'Serca',
    clear_data: 'Cancela dati',
    info_title: 'Informassion',
    how_it_works: 'Come che funsiona',
    legal_warning: 'Le foto false o inaproprie le xe un ilesito.'
  }
};

// Funzioni principali
function toggleLangMenu() {
  const menu = document.getElementById('langMenu');
    if (menu) {
    menu.classList.toggle('open');
}
}

function setLanguage(lang) {
  currentLang = lang;
  localStorage.setItem('language', currentLang);
  updateUILanguage();
  updateButtonText();
  // Chiudi il menu
  const menu = document.getElementById('langMenu');
  menu.classList.remove('open');
}

function updateUILanguage() {
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (translations[currentLang] && translations[currentLang][key]) {
      if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
        if (el.placeholder !== undefined) {
          el.placeholder = translations[currentLang][key];
        } else {
          el.value = translations[currentLang][key];
        }
      } else {
        el.textContent = translations[currentLang][key];
      }
    }
  });
}

function updateButtonText() {
  const langText = document.getElementById('langText');
  if (langText) {
    const codes = { it: 'IT', en: 'EN', es: 'ES', fr: 'FR', de: 'DE', vec: 'VEC' };
    langText.textContent = codes[currentLang] || 'IT';
  }
}

function initLanguage() {
  updateUILanguage();
  updateButtonText();
  // Chiudi menu se si clicca fuori
  document.addEventListener('click', function(e) {
    const dropdown = document.querySelector('.lang-dropdown');
    const menu = document.getElementById('langMenu');
    if (dropdown && menu && !dropdown.contains(e.target)) {
      menu.classList.remove('open');
    }
  });
}

document.addEventListener('DOMContentLoaded', initLanguage);
